//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cauthu
    {
        public int Id { get; set; }
        public string TenCauThu { get; set; }
        public string Gioitinh { get; set; }
        public System.DateTime Ngaysinh { get; set; }
        public string Nickname { get; set; }
        public string Quequan { get; set; }
        public string Chieucao { get; set; }
        public string Vitri { get; set; }
        public string Soao { get; set; }
        public string clb { get; set; }
    }
}
